### ISSUE TITLE
Todo's

### ISSUE THREAD

**Issue by awei82** [awei82/linkedin-recents#1]
- [x] Save visits to company profiles
- [x] Add search functionality
- [x] Create Profile model
- [x] Fix storage ordering
- [x] update HMR and build directories

Later
- [ ] Refactor to Typescript
